const { getIcon } = require("obsidian");

// Shared constants plus small pure helpers for dates, labels, Markdown, and DOM controls.
const VIEW_TYPE = "kanux-view";
const LEGACY_CARD_FOLDER = "Kanban Cards";
const LEGACY_BOARD_INDEX_SUFFIX = "Kanux Board.md";
const BOARD_INDEX_MARKER = "Generated by Kanux so board cards stay connected in Obsidian graph view.";
const KANUX_ICON = "kanux";
const KANUX_ICON_SVG = `
  <g fill="none" stroke="currentColor" stroke-width="7" stroke-linecap="round" stroke-linejoin="round">
    <rect x="14" y="16" width="20" height="68" rx="6" />
    <rect x="40" y="16" width="20" height="52" rx="6" />
    <rect x="66" y="16" width="20" height="38" rx="6" />
    <path d="M21 31h6" />
    <path d="M47 31h6" />
    <path d="M73 31h6" />
  </g>
`;
const LIST_DRAG_TYPE = "application/x-kanux-list";
const IMAGE_EXTENSIONS = ["png", "jpg", "jpeg", "gif", "webp", "svg", "bmp", "avif", "ico"];
const DEFAULT_LABEL_COLOR = "#2f6fd6";
const LABEL_COLORS = [
  "#1f6f4a", "#8a6f00", "#a64b00", "#8b2a24", "#6f338f",
  "#247b55", "#9a7600", "#b85f00", "#be332b", "#8a3db0",
  "#54c99b", "#e5bd12", "#ffa51a", "#f46b66", "#c878ee",
  "#1b4078", "#1f7082", "#426226", "#67264f", "#5d6369",
  "#2465c7", "#2b7c8e", "#4f7822", "#a33e78", "#73787f",
  "#68a0ee", "#70c1d8", "#96c949", "#dc6ab5", "#a3a6aa",
];
// Default list-color sequence. Grey → blue → green first so a fresh board's
// To do / Doing / Done reads the way most people expect.
const LIST_COLORS = ["#94a3b8", "#3b82f6", "#22c55e", "#f59e0b", "#ef4444", "#8b5cf6", "#14b8a6", "#ec4899"];

// How a board draws the code chip on its cards. One look for the whole board,
// chosen in Customize, so every card's identifier reads the same way.
const CODE_STYLES = ["outline", "filled", "soft", "plain"];
const CODE_PLACEMENTS = ["inline", "above"];
const DEFAULT_CODE_LOOK = { style: "outline", color: "", placement: "inline" };
const DEFAULT_CHECKLIST_TITLE = "Checklist";
const DEFAULT_CHECKLIST_COLOR = LIST_COLORS[1];
const DEFAULT_APPEARANCE = {
  preset: "obsidian",
  colorScheme: "theme",
  surfaceScheme: "theme",
  density: "normal",
  fontScale: 1,
  labels: {
    displayMode: "expanded",
  },
  background: {
    type: "theme",
    color: "#1e1e1e",
    gradientStart: "#172033",
    gradientEnd: "#0f172a",
    imagePath: "",
    imageSource: "vault",
    imageFit: "original",
    imageFitVersion: 3,
    overlayOpacity: 0.35,
  },
  cards: {
    useTheme: true,
    background: "#25262a",
    hoverBackground: "#30343b",
    verticalGap: 8,
    titleSize: 18,
    borderRadius: 9,
    shadow: "medium",
  },
  lists: {
    useTheme: true,
    background: "#161719",
    columnGap: 12,
    topBorderWidth: 3,
    showColorDot: true,
    borderRadius: 12,
  },
  motion: {
    enabled: true,
  },
  codes: { ...DEFAULT_CODE_LOOK },
};

/**
 * Minimal saved-data shape used when the plugin starts with no existing board.
 *
 * Cards are stored in a top-level map and lists keep card ids. This makes
 * moving cards between lists cheap while still letting each card have one
 * Markdown file on disk.
 */
const DEFAULT_DATA = {
  version: 1,
  activeBoardId: "",
  syncDeckEnabled: true,
  completionSound: true,
  compactLabels: false,
  labelDisplayMode: "expanded",
  appearance: DEFAULT_APPEARANCE,
  appearancePresets: [],
  layoutMigrated: false,
  boards: [],
  cards: {},
  labels: [],
};

function clone(value) {
  return JSON.parse(JSON.stringify(value));
}

function uid(prefix) {
  return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
}

function textLine(value) {
  return String(value || "").replace(/\r?\n/g, " ").trim();
}

/**
 * Accepts only the storage format used in card frontmatter: YYYY-MM-DD.
 */
function cleanDate(value) {
  const date = textLine(value);
  return /^\d{4}-\d{2}-\d{2}$/.test(date) ? date : "";
}

function cleanColor(value) {
  const color = textLine(value).replace(/^["']|["']$/g, "");
  return /^#[0-9a-f]{6}$/i.test(color) ? color : "";
}

function dateFromISO(value) {
  const date = cleanDate(value);
  if (!date) return null;

  const [year, month, day] = date.split("-").map(Number);
  return new Date(year, month - 1, day);
}

function isoFromDate(date) {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

function addMonths(date, amount) {
  return new Date(date.getFullYear(), date.getMonth() + amount, 1);
}

function shortDateLabel(value) {
  const date = dateFromISO(value);
  if (!date) return "";

  return new Intl.DateTimeFormat(undefined, { day: "numeric", month: "short" })
    .format(date)
    .replace(/\.$/, "");
}

function fieldDateLabel(value) {
  const date = dateFromISO(value);
  if (!date) return "D.M.YYYY";

  const day = String(date.getDate()).padStart(2, "0");
  const month = String(date.getMonth() + 1).padStart(2, "0");
  return `${day}.${month}.${date.getFullYear()}`;
}

function dateRangeLabel(startDate, dueDate) {
  const start = cleanDate(startDate);
  const due = cleanDate(dueDate);
  if (start && due && start !== due) return `${shortDateLabel(start)} - ${shortDateLabel(due)}`;
  return shortDateLabel(due || start);
}

function parseBoolean(value) {
  const normalized = textLine(value).toLowerCase();
  return ["true", "yes", "1", "x", "done"].includes(normalized);
}

function labelKey(label) {
  return textLine(typeof label === "string" ? label : label && label.name).toLowerCase();
}

function cleanLabelName(label) {
  const name = textLine(typeof label === "string" ? label : label && label.name);
  if (name === "---" || /^(kanban-card-id|kanban-board-id|kanban-list-id|completed|start|due):/i.test(name)) return "";
  return name;
}

/**
 * Builds a readable vault-safe card filename from a title.
 */
function cardFileBaseName(value) {
  const name = textLine(value || "Card")
    .replace(/[\\/:*?"<>|#^[\]]/g, " ")
    .replace(/\s+/g, " ")
    .replace(/^\.+|\.+$/g, "")
    .trim()
    .slice(0, 80);

  return name || "Card";
}

function tagPart(value) {
  return textLine(value || "item")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 48) || "item";
}

function kanuxListTag(boardName, listTitle) {
  return `kanux/${tagPart(boardName)}/${tagPart(listTitle)}`;
}

function imageTarget(raw) {
  return String(raw || "")
    .trim()
    .replace(/^<|>$/g, "")
    .split("|")[0]
    .split("#")[0]
    .split("?")[0]
    .trim();
}

function isImagePath(value) {
  const match = imageTarget(value).toLowerCase().match(/\.([a-z0-9]+)$/);
  return !!(match && IMAGE_EXTENSIONS.includes(match[1]));
}

function imageRefsFromMarkdown(markdown) {
  const text = String(markdown || "");
  const refs = [];
  let match;

  const wikiRe = /!\[\[([^\]]+)\]\]/g;
  while ((match = wikiRe.exec(text))) {
    const target = imageTarget(match[1]);
    if (isImagePath(target)) refs.push({ target, markup: match[0] });
  }

  const mdRe = /!\[[^\]]*]\(([^)]+)\)/g;
  while ((match = mdRe.exec(text))) {
    const target = imageTarget(match[1]);
    if (isImagePath(target) || /^https?:\/\//i.test(target)) refs.push({ target, markup: match[0] });
  }

  return refs;
}

function stripImageEmbeds(markdown) {
  let text = String(markdown || "");
  imageRefsFromMarkdown(text).forEach((ref) => {
    text = text.replace(ref.markup, "");
  });
  return text.replace(/\n{3,}/g, "\n\n").trim();
}

// Resizable embeds store their width in Obsidian's own image-size syntax:
// ![[img.png|300]] for wiki embeds, ![alt|300](url) for markdown embeds — so a
// resized card image renders at the same width when the note opens in Obsidian.
const IMAGE_SIZE_RE = /^(\d+)(x\d+)?$/i;

// Width (px) stored in an image embed's markup, or null when unsized.
function imageSizeFromMarkup(markup) {
  const text = String(markup || "");
  let candidate = null;
  const wiki = text.match(/^!\[\[([^\]]+)\]\]$/);
  if (wiki) {
    const parts = wiki[1].split("|");
    if (parts.length > 1) candidate = parts[parts.length - 1];
  } else {
    const md = text.match(/^!\[([^\]]*)\]\(([^)]+)\)$/);
    if (md) candidate = md[1].split("|").pop();
  }
  if (!candidate) return null;
  const match = candidate.trim().match(IMAGE_SIZE_RE);
  return match ? parseInt(match[1], 10) : null;
}

// Returns the embed markup with its size segment set to `width` px; a falsy
// width clears the size so the image renders at its natural/full width. Only
// a trailing size-like segment is touched — aliases and titles survive.
function imageMarkupWithSize(markup, width) {
  const text = String(markup || "");
  const size = width > 0 ? String(Math.round(width)) : "";
  const wiki = text.match(/^!\[\[([^\]]+)\]\]$/);
  if (wiki) {
    const parts = wiki[1].split("|");
    if (parts.length > 1 && IMAGE_SIZE_RE.test(parts[parts.length - 1].trim())) parts.pop();
    if (size) parts.push(size);
    return `![[${parts.join("|")}]]`;
  }
  const md = text.match(/^!\[([^\]]*)\]\(([^)]+)\)$/);
  if (md) {
    const parts = md[1].split("|");
    if (IMAGE_SIZE_RE.test(parts[parts.length - 1].trim())) parts.pop();
    const alt = parts.join("|").trim();
    const sized = size ? (alt ? `${alt}|${size}` : size) : alt;
    return `![${sized}](${md[2]})`;
  }
  return text;
}

// Moves an entry that lives in `source` so it lands at `insertionIndex` of
// `target` (which may be the same array). The index is measured before the
// entry is removed, so drag & drop callers can point at the slot they see.
function moveArrayEntry(source, target, entry, insertionIndex) {
  const sourceIndex = source.indexOf(entry);
  if (sourceIndex < 0) return false;
  let nextIndex = insertionIndex;
  source.splice(sourceIndex, 1);
  if (source === target && sourceIndex < nextIndex) nextIndex -= 1;
  nextIndex = Math.max(0, Math.min(nextIndex, target.length));
  target.splice(nextIndex, 0, entry);
  return true;
}

function createElement(tag, className, text) {
  const element = document.createElement(tag);
  if (className) element.className = className;
  if (text !== undefined) element.textContent = text;
  return element;
}

/**
 * The chip a card's code is drawn in. `look` is the board's `appearance.codes`;
 * it rides on the element — a class per style and placement, the colour as a
 * variable — so the board, the table, the library and the template editor's
 * preview all draw a code the same way.
 */
function cardCodeChip(code, look) {
  const chip = createElement("span", "ot-card-code", code);
  const clean = normalizeCodeLook(look);
  chip.classList.add(`is-${clean.style}`, `is-${clean.placement}`);
  if (clean.color) chip.style.setProperty("--ot-code-color", clean.color);
  // An identifier, not prose: keep machine translation off it.
  chip.setAttribute("translate", "no");
  return chip;
}

function hasDragType(event, type) {
  const types = event.dataTransfer && event.dataTransfer.types;
  return !!types && (Array.from(types).includes(type) || (types.contains && types.contains(type)));
}

const ICON_ALIASES = {
  ellipsis: ["ellipsis", "more-horizontal"],
  "check-square": ["square-check", "check-square"],
  "plus-square": ["square-plus", "plus-square"],
  "layout-dashboard": ["layout-dashboard", "panel-top", "grid-2x2"],
  "calendar-days": ["calendar-days", "calendar"],
  pencil: ["pencil", "edit-3", "edit"],
  trash: ["trash-2", "trash"],
  "help-circle": ["circle-help", "help-circle"],
  "alert-triangle": ["triangle-alert", "alert-triangle"],
  unlock: ["lock-open", "unlock"],
};

const DEFAULT_ICON_NAMES = ["circle-help", "help-circle", "circle"];

function renderIcon(element, icon) {
  const candidates = ICON_ALIASES[icon] || [icon];
  const svg = firstAvailableIcon([...candidates, ...DEFAULT_ICON_NAMES]);
  element.replaceChildren(...(svg ? [svg] : []));
}

function firstAvailableIcon(iconNames) {
  for (const iconName of iconNames) {
    const svg = getIcon(iconName);
    if (svg) return svg;
  }
  return null;
}

function iconButton(icon, label, onClick) {
  const button = createElement("button", "ot-icon-button");
  button.type = "button";
  button.title = label;
  button.setAttribute("aria-label", label);
  renderIcon(button, icon);
  button.addEventListener("click", onClick);
  return button;
}

function textButton(icon, label, onClick, className = "") {
  const button = createElement("button", `ot-text-button ${className}`.trim());
  button.type = "button";

  const iconSlot = createElement("span", "ot-button-icon");
  renderIcon(iconSlot, icon);

  button.append(iconSlot, createElement("span", "", label));
  button.addEventListener("click", onClick);
  return button;
}

function addButtonIcon(button, icon) {
  const iconSlot = createElement("span", "ot-button-icon");
  renderIcon(iconSlot, icon);
  button.prepend(iconSlot);
  button.classList.add("ot-button-with-icon");
  return button;
}

/**
 * Reads a second-level Markdown section body, stopping before the next H2.
 */
// The real section headings in a card note. A "## ..." line only ends a section
// when it's one of these AND outside a fenced code block — so a user can write a
// "## " heading (or a "## " comment inside a ``` block) in Details without the
// text after it being silently truncated.
const CARD_SECTION_HEADINGS = ["Details", "Detaylar", "Checklist", "Yapılacaklar", "Kontrol listesi"];

function getSection(markdown, heading, boundaries) {
  const marker = `## ${heading}`;
  const start = String(markdown || "").indexOf(marker);
  if (start === -1) return "";

  const body = String(markdown).slice(start + marker.length);
  const boundarySet = Array.isArray(boundaries) && boundaries.length
    ? new Set(boundaries.map((h) => `## ${h}`))
    : null;

  const kept = [];
  let inFence = false;
  for (const line of body.split("\n")) {
    if (/^\s*(```|~~~)/.test(line)) { // opening/closing code fence
      inFence = !inFence;
      kept.push(line);
      continue;
    }
    if (!inFence) {
      const isBoundary = boundarySet
        ? boundarySet.has(line.trim())
        : /^##\s/.test(line.trimStart());
      if (isBoundary) break;
    }
    kept.push(line);
  }
  return kept.join("\n").trim();
}

function getSectionAny(markdown, headings) {
  for (const heading of headings) {
    const section = getSection(markdown, heading, CARD_SECTION_HEADINGS);
    if (section) return section;
  }
  return "";
}

/**
 * Converts Markdown checklist lines into the card checklist model.
 *
 * Non-checkbox lines are kept as unchecked items so notes written by hand do
 * not silently lose useful text.
 */
function parseChecklist(text) {
  return String(text || "")
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean)
    .map(parseChecklistLine)
    .filter((item) => item.text);
}

function parseChecklistLine(line) {
  const { content: lineWithoutId, id } = extractChecklistItemId(line);
  const { content, assignee } = extractChecklistAssignee(lineWithoutId);
  const checkbox = content.match(/^(?:-\s*)?\[([ xX])\]\s*(.*)$/);
  const done = checkbox ? checkbox[1].toLowerCase() === "x" : false;
  const value = checkbox ? checkbox[2].trim() : content.replace(/^- /, "").trim();
  return { id, done, assignee, ...parseChecklistItemValue(value) };
}

// The id comment is written last on the line, so it is extracted before the
// assignee comment that precedes it.
function extractChecklistItemId(line) {
  const metadata = line.match(/\s*<!--kanux-item-id:([A-Za-z0-9_-]+)-->\s*$/);
  if (!metadata) return { content: line, id: "" };
  return { content: line.slice(0, metadata.index), id: metadata[1] };
}

function extractChecklistAssignee(line) {
  const metadata = line.match(/\s*<!--@(.*?)-->\s*$/);
  if (!metadata) return { content: line, assignee: null };

  const [email = "", name = "", color = ""] = String(metadata[1] || "").split("|");
  const cleanEmail = email.trim();
  return {
    content: line.slice(0, metadata.index).trim(),
    assignee: cleanEmail
      ? { email: cleanEmail, name: name.trim(), color: color.trim() }
      : null,
  };
}

// A checklist item can be a normal string or a wikilink to a Markdown note.
// Only a link that occupies the whole item is treated as file-backed; inline
// links inside ordinary item text remain ordinary text.
function parseChecklistItemValue(value) {
  const text = String(value || "").trim();
  const link = text.match(/^\[\[([^|\]]+)(?:\|([^\]]+))?\]\]$/);
  if (!link) return { text, filePath: "" };

  const target = textLine(link[1]).split("#")[0].trim();
  if (!target) return { text, filePath: "" };
  const filePath = /\.md$/i.test(target) ? target : `${target}.md`;
  const fallback = target.split("/").pop().replace(/\.md$/i, "") || "Checklist item";
  return { text: textLine(link[2]) || fallback, filePath };
}

/**
 * Returns the user-authored body of a checklist item note.
 *
 * Frontmatter is never part of the preview. Notes created by Kanux also
 * contain a generated H1 and card backlink; those lines are removed only when
 * the note identifies itself as a managed checklist item.
 */
function checklistItemNoteBody(markdown) {
  const { frontmatter, body } = splitFrontmatter(markdown);
  const managed = /(?:^|\r?\n)[ \t]*kanux-checklist-item[ \t]*:[ \t]*true[ \t]*(?:#.*)?(?:\r?\n|$)/i.test(frontmatter);
  if (!managed) return body.trim();

  return stripManagedChecklistHeader(body);
}

function checklistItemNoteWithBody(markdown, nextBody) {
  const source = String(markdown || "").replace(/^\uFEFF/, "");
  const { frontmatter, body } = splitFrontmatter(source);
  const managed = /(?:^|\r?\n)[ \t]*kanux-checklist-item[ \t]*:[ \t]*true[ \t]*(?:#.*)?(?:\r?\n|$)/i.test(frontmatter);
  const prefix = source.slice(0, source.length - body.length);
  const content = String(nextBody || "").trim();

  if (!managed) return `${prefix}${content}\n`;

  const boilerplate = managedChecklistBoilerplate(body);
  return `${prefix}${boilerplate}${content ? `\n\n${content}` : ""}\n`;
}

function managedChecklistBoilerplate(body) {
  const lines = String(body || "").split(/\r?\n/);
  let index = 0;
  while (index < lines.length && !lines[index].trim()) index += 1;
  if (index < lines.length && /^#[ \t]+\S/.test(lines[index])) index += 1;
  while (index < lines.length && !lines[index].trim()) index += 1;
  if (index < lines.length && /^Card:[ \t]*\[\[[^\]]+\]\][ \t]*$/i.test(lines[index])) index += 1;
  return lines.slice(0, index).join("\n").trim();
}

function splitFrontmatter(markdown) {
  const document = String(markdown || "").replace(/^\uFEFF/, "");
  const match = document.match(/^---[ \t]*\r?\n([\s\S]*?)\r?\n---[ \t]*(?:\r?\n|$)/);
  if (!match) return { frontmatter: "", body: document };
  return { frontmatter: match[1], body: document.slice(match[0].length) };
}

function stripManagedChecklistHeader(body) {
  const lines = body.split(/\r?\n/);
  while (lines.length && !lines[0].trim()) lines.shift();
  if (lines.length && /^#[ \t]+\S/.test(lines[0])) lines.shift();
  while (lines.length && !lines[0].trim()) lines.shift();
  if (lines.length && /^Card:[ \t]*\[\[[^\]]+\]\][ \t]*$/i.test(lines[0])) lines.shift();
  return lines.join("\n").trim();
}

/**
 * Normalizes the named checklist collection used by current cards.
 *
 * `legacyItems` keeps data.json files from versions that stored one flat
 * `checklist` array compatible. An explicitly supplied empty `checklists`
 * array remains empty; only a missing collection receives the legacy/default
 * Checklist group.
 */
function normalizeChecklists(checklists, legacyItems) {
  const source = Array.isArray(checklists)
    ? checklists
    : [{ title: DEFAULT_CHECKLIST_TITLE, items: Array.isArray(legacyItems) ? legacyItems : [] }];

  // Ids must stay unique within the card so external references (for example
  // future card dependencies) always resolve to exactly one group or item.
  const seenIds = new Set();
  return source
    .filter((group) => group && typeof group === "object")
    .map((group, index) => normalizeChecklistGroup(group, index, seenIds));
}

function normalizeChecklistGroup(group, index, seenIds) {
  return {
    id: uniqueChecklistId(group.id, "checklist", seenIds),
    title: textLine(group.title) || `${DEFAULT_CHECKLIST_TITLE} ${index + 1}`,
    color: cleanColor(group.color) || DEFAULT_CHECKLIST_COLOR,
    collapsed: !!group.collapsed,
    description: cleanChecklistDescription(group.description),
    dependencies: normalizeDependencies(group.dependencies),
    items: (Array.isArray(group.items) ? group.items : [])
      .map((item) => normalizeChecklistItem(item, seenIds))
      .filter((item) => item.text),
  };
}

function cleanChecklistDescription(value) {
  return String(value || "").replace(/\r\n?/g, "\n").trim();
}

function normalizeChecklistItem(item, seenIds) {
  return {
    id: uniqueChecklistId(item && item.id, "item", seenIds),
    done: !!(item && item.done),
    text: textLine(item && item.text),
    filePath: textLine(item && item.filePath),
    assignee: normalizeChecklistAssignee(item && item.assignee),
  };
}

/**
 * Ids round-trip through Markdown comments, so hand edits can produce ids
 * with invalid characters or duplicates from copied lines. Both cases receive
 * a fresh id; every kept or generated id is recorded in `seenIds`.
 */
function uniqueChecklistId(value, prefix, seenIds) {
  const candidate = cleanKanuxId(value);
  const id = candidate && !seenIds.has(candidate) ? candidate : uid(prefix);
  seenIds.add(id);
  return id;
}

function cleanKanuxId(value) {
  const id = textLine(value);
  return /^[A-Za-z0-9_-]+$/.test(id) ? id : "";
}

function normalizeChecklistAssignee(assignee) {
  if (!assignee || !assignee.email) return null;
  return {
    email: textLine(assignee.email),
    name: textLine(assignee.name),
    color: textLine(assignee.color),
  };
}

/**
 * Parses the body of `## Checklist`.
 *
 * Current notes use H3 headings for named groups. Notes from older versions
 * contain task items directly under H2 and become one group named Checklist.
 */
function parseChecklists(text) {
  const groups = [];
  let pendingGroup = null;

  for (const line of String(text || "").split(/\r?\n/)) {
    const heading = parseChecklistHeading(line);
    if (heading) {
      appendParsedChecklist(groups, pendingGroup);
      pendingGroup = { ...heading, lines: [] };
      continue;
    }
    if (!pendingGroup) pendingGroup = { title: DEFAULT_CHECKLIST_TITLE, color: "", lines: [] };
    pendingGroup.lines.push(line);
  }
  appendParsedChecklist(groups, pendingGroup);

  return groups.length ? groups : normalizeChecklists(undefined, []);
}

function parseChecklistHeading(line) {
  const heading = line.match(/^###\s+(.+?)\s*$/);
  if (!heading) return null;
  return extractChecklistHeadingMetadata(heading[1]);
}

/**
 * Strips the trailing metadata comments (color, id, depends, collapsed) that
 * round-trip group data the visible heading text cannot carry. They may appear
 * in any order; values are validated downstream by cleanColor/cleanKanuxId.
 */
function extractChecklistHeadingMetadata(heading) {
  const result = { title: heading, color: "", id: "", dependencies: "", collapsed: false };
  const metadata = /\s*<!--kanux-checklist-(color|id|depends|collapsed):([^>\s]+)-->\s*$/;
  for (let match = result.title.match(metadata); match; match = result.title.match(metadata)) {
    if (match[1] === "color") result.color = match[2];
    else if (match[1] === "id") result.id = match[2];
    else if (match[1] === "collapsed") result.collapsed = parseBoolean(match[2]);
    else result.dependencies = match[2];
    result.title = result.title.slice(0, match.index).trim();
  }
  return result;
}

function appendParsedChecklist(groups, group) {
  if (!group) return;
  const { description, itemLines } = splitChecklistDescription(group.lines);
  groups.push({
    id: cleanKanuxId(group.id) || uid("checklist"),
    title: textLine(group.title) || `${DEFAULT_CHECKLIST_TITLE} ${groups.length + 1}`,
    color: cleanColor(group.color) || DEFAULT_CHECKLIST_COLOR,
    collapsed: !!group.collapsed,
    description,
    dependencies: parseDependencies(group.dependencies),
    items: parseChecklist(itemLines.join("\n")),
  });
}

/**
 * Leading plain-text lines under a group heading are its description; the
 * first item-like line (checkbox or dash bullet) starts the items. Plain
 * lines that appear after that keep the legacy behavior of becoming
 * unchecked items, so hand-written notes never lose text silently.
 */
function splitChecklistDescription(lines) {
  const source = Array.isArray(lines) ? lines : [];
  const firstItemIndex = source.findIndex(isChecklistItemLine);
  const boundary = firstItemIndex === -1 ? source.length : firstItemIndex;
  const description = cleanChecklistDescription(
    source.slice(0, boundary).map(unescapeChecklistDescriptionLine).join("\n"),
  );
  return { description, itemLines: source.slice(boundary) };
}

function isChecklistItemLine(line) {
  return /^\s*(?:-|\[[ xX]\])/.test(line);
}

// A description line that starts like a heading would split the group (or the
// card section) when the note is parsed again, and one that starts like a
// task would turn into an item. The marker is escaped with a backslash —
// which Markdown renders invisibly — and removed again on read.
function escapeChecklistDescriptionLine(line) {
  return line.replace(/^(\s*)([#\-\[])/, "$1\\$2");
}

function unescapeChecklistDescriptionLine(line) {
  return line.replace(/^(\s*)\\([#\-\[])/, "$1$2");
}

function checklistToText(items) {
  return (items || [])
    .map((item) => `[${item.done ? "x" : " "}] ${checklistItemMarkdown(item)}`)
    .join("\n");
}

function checklistItemMarkdown(item) {
  const title = textLine(item && item.text);
  const filePath = textLine(item && item.filePath);
  if (!filePath) return title;
  const target = filePath.replace(/\.md$/i, "").replace(/[|\[\]]/g, " ").trim();
  const alias = title.replace(/[|\[\]]/g, " ").trim() || target.split("/").pop() || "Checklist item";
  return `[[${target}|${alias}]]`;
}

function checklistToMarkdown(items) {
  return (items || [])
    .map((item) => {
      let line = `- [${item.done ? "x" : " "}] ${checklistItemMarkdown(item)}`;
      const assignee = item.assignee;
      if (assignee && assignee.email) {
        // Per-item member assignment, hidden in an HTML comment so it round-trips
        // and stays invisible in Markdown preview.
        line += ` <!--@${safeCommentValue(assignee.email)}|${safeCommentValue(assignee.name)}|${safeCommentValue(assignee.color)}-->`;
      }
      const id = cleanKanuxId(item.id);
      if (id) line += ` <!--kanux-item-id:${id}-->`;
      return line;
    })
    .join("\n");
}

function safeCommentValue(value) {
  return String(value || "").replace(/[|>]/g, " ").trim();
}

function checklistsToMarkdown(checklists) {
  return normalizeChecklists(checklists, [])
    .map((group) => {
      const dependencies = serializeDependencies(group.dependencies);
      const heading = `### ${textLine(group.title) || DEFAULT_CHECKLIST_TITLE}`
        + ` <!--kanux-checklist-color:${cleanColor(group.color) || DEFAULT_CHECKLIST_COLOR}-->`
        + ` <!--kanux-checklist-id:${group.id}-->`
        + (dependencies ? ` <!--kanux-checklist-depends:${dependencies}-->` : "")
        // Written only when folded, so notes that never fold never change.
        + (group.collapsed ? " <!--kanux-checklist-collapsed:true-->" : "");
      const description = group.description.split("\n").map(escapeChecklistDescriptionLine).join("\n");
      const items = checklistToMarkdown(group.items);
      return [heading, description, items].filter(Boolean).join("\n");
    })
    .join("\n\n");
}

/**
 * Checklist groups prepared for reuse: nothing ticked, nothing still linked to
 * the notes of the card they were copied from, no dependencies pointing at that
 * card's neighbours, and no ids, so whoever normalizes them next mints a fresh
 * set instead of every copy sharing one.
 */
function blankChecklists(checklists) {
  return normalizeChecklists(checklists, []).map((group) => ({
    title: group.title,
    color: group.color,
    description: group.description,
    dependencies: [],
    items: group.items.map((item) => ({
      text: item.text,
      done: false,
      filePath: "",
      assignee: item.assignee,
    })),
  }));
}

/**
 * Where the caret belongs in a template description: inside the first blank of
 * "As a [ ] I want [ ] so that [ ]". A pair of brackets that is all a list
 * marker carries is a task checkbox rather than a blank, so it is skipped.
 * Returns -1 when the text has nothing to fill in.
 */
function firstPlaceholderIndex(markdown) {
  const text = String(markdown || "");
  const gap = /\[[ \t]*\]/g;
  for (let match = gap.exec(text); match; match = gap.exec(text)) {
    const lineStart = text.lastIndexOf("\n", match.index) + 1;
    if (!/^\s*[-*+]\s*$/.test(text.slice(lineStart, match.index))) return match.index + 1;
  }
  return -1;
}

/* ---- Template numbering ---- */
// A template can stamp every card it makes with a running code — BUG-014 — so
// a card can be named out loud. The counter lives in the template note, so it
// survives a reload and syncs with the vault like everything else.
const NUMBERING_KEYS = {
  prefix: "kanux-id-prefix",
  separator: "kanux-id-separator",
  next: "kanux-id-next",
  pad: "kanux-id-pad",
};
const MAX_NUMBER_PAD = 8;

// What sits between the prefix and the number, stored by name rather than as
// the character itself: a bare "-" is a YAML list marker and a bare "#" opens
// a comment, so neither can be written into a note's frontmatter as it is.
const CODE_SEPARATORS = [
  { id: "dash", char: "-", label: "Dash" },
  { id: "dot", char: ".", label: "Dot" },
  { id: "slash", char: "/", label: "Slash" },
  { id: "hash", char: "#", label: "Hash" },
  { id: "underscore", char: "_", label: "Underscore" },
  { id: "none", char: "", label: "None" },
];
const DEFAULT_SEPARATOR = "dash";

/** A separator's id from its name or its literal character; the dash when it is neither. */
function cleanSeparator(value) {
  const text = textLine(value);
  const match = CODE_SEPARATORS.find((separator) => separator.id === text.toLowerCase() || (separator.char && separator.char === text));
  return match ? match.id : DEFAULT_SEPARATOR;
}

function separatorChar(id) {
  const match = CODE_SEPARATORS.find((separator) => separator.id === id);
  return match ? match.char : "-";
}

/** The look with every field filled in; anything unknown falls back to the default. */
function normalizeCodeLook(value) {
  const source = value && typeof value === "object" ? value : {};
  return {
    style: CODE_STYLES.includes(source.style) ? source.style : DEFAULT_CODE_LOOK.style,
    color: cleanColor(source.color).toLowerCase(),
    placement: CODE_PLACEMENTS.includes(source.placement) ? source.placement : DEFAULT_CODE_LOOK.placement,
  };
}

/** Numbering is on when the note carries a next number; nothing else is required. */
function parseTemplateNumbering(markdown) {
  const read = (key) => {
    const match = String(markdown || "").match(new RegExp(`(?:^|\\r?\\n)[ \\t]*${key}[ \\t]*:(.*)`));
    return match ? textLine(match[1]) : "";
  };
  const next = numberOrNull(read(NUMBERING_KEYS.next));
  if (next === null) return null;
  return normalizeNumbering({
    prefix: read(NUMBERING_KEYS.prefix),
    separator: read(NUMBERING_KEYS.separator),
    next,
    pad: numberOrNull(read(NUMBERING_KEYS.pad)),
  });
}

function normalizeNumbering(numbering) {
  if (!numbering) return null;
  const next = Math.max(0, Math.floor(numberOrNull(numbering.next) || 0));
  const pad = Math.min(MAX_NUMBER_PAD, Math.max(1, Math.floor(numberOrNull(numbering.pad) || 1)));
  // No spaces in a prefix: the code is stored as one token, so a space typed
  // here would make the preview and the stored code disagree.
  return {
    prefix: textLine(numbering.prefix).replace(/\s+/g, ""),
    separator: cleanSeparator(numbering.separator),
    next,
    pad,
  };
}

/** The code a card would carry: "BUG-014", or "014" when there is no prefix. */
function formatCardCode(numbering, value) {
  const clean = normalizeNumbering(numbering);
  if (!clean) return "";
  const number = numberOrNull(value);
  const counter = number === null ? clean.next : Math.max(0, Math.floor(number));
  const digits = String(counter).padStart(clean.pad, "0");
  return clean.prefix ? `${clean.prefix}${separatorChar(clean.separator)}${digits}` : digits;
}


/**
 * Rewrites just the numbering keys of a template note, leaving the rest of the
 * file alone. A template is a note people edit by hand, so re-serializing it
 * from the parsed model would quietly drop anything the parser does not carry.
 * Passing null turns numbering off. Returns the text unchanged when the note
 * has no frontmatter to write into.
 */
function withNumbering(markdown, numbering) {
  const text = String(markdown || "");
  const block = text.match(/^(---\r?\n)([\s\S]*?)(^---[ \t]*$)/m);
  if (!block) return text;

  const ending = text.includes("\r\n") ? "\r\n" : "\n";
  const keys = Object.values(NUMBERING_KEYS);
  const kept = block[2]
    .split(/\r?\n/)
    .filter((line) => !keys.some((key) => new RegExp(`^[ \\t]*${key}[ \\t]*:`).test(line)));
  while (kept.length && !kept[kept.length - 1].trim()) kept.pop();

  const clean = normalizeNumbering(numbering);
  if (clean) {
    kept.push(`${NUMBERING_KEYS.prefix}: ${clean.prefix}`);
    kept.push(`${NUMBERING_KEYS.separator}: ${clean.separator}`);
    kept.push(`${NUMBERING_KEYS.next}: ${clean.next}`);
    kept.push(`${NUMBERING_KEYS.pad}: ${clean.pad}`);
  }

  return text.slice(0, block.index) + block[1] + kept.join(ending) + ending + block[3] + text.slice(block.index + block[0].length);
}

/**
 * A card's code as it is stored: one token, no spaces. The code identifies the
 * card, so it must survive a round trip through frontmatter unchanged.
 */
function cleanCardCode(value) {
  return textLine(value).replace(/\s+/g, "");
}

/**
 * The number inside a card's code — 14 for "BUG-014" — or -1 when the code did
 * not come from this template. The prefix is matched literally, so a template
 * prefixed "A.B" cannot claim the cards of one prefixed "AXB".
 */
function cardCodeNumber(code, numbering) {
  const clean = normalizeNumbering(numbering);
  if (clean === null) return -1;
  const head = clean.prefix ? `${clean.prefix}${separatorChar(clean.separator)}`.replace(/[.*+?^${}()|[\]\\]/g, "\\$&") : "";
  const match = cleanCardCode(code).match(new RegExp(`^${head}(\\d+)$`));
  return match ? Number(match[1]) : -1;
}

function checklistItems(checklists) {
  return (Array.isArray(checklists) ? checklists : [])
    .flatMap((group) => (group && Array.isArray(group.items) ? group.items : []));
}

function checklistStats(items) {
  const source = Array.isArray(items) && items.some((item) => item && Array.isArray(item.items))
    ? checklistItems(items)
    : (items || []);
  const total = source.length;
  const done = source.filter((item) => item.done).length;
  return {
    done,
    total,
    percent: total ? Math.round((done / total) * 100) : 0,
  };
}

// ---- Card dependencies ----
// A dependency points one card (or one checklist group) at another card and
// decides how hard an unmet dependency gates the actions it guards.
const DEPENDENCY_BLOCK_NONE = "none";
const DEPENDENCY_BLOCK_WARN = "warn";
const DEPENDENCY_BLOCK_TOTAL = "block";
// Weakest to strongest: a gate reports the strongest mode still unmet. How each
// one is named and drawn belongs to the picker that offers them, not here.
const DEPENDENCY_BLOCK_MODES = [DEPENDENCY_BLOCK_NONE, DEPENDENCY_BLOCK_WARN, DEPENDENCY_BLOCK_TOTAL];
// A dependency is met once the card it points at is completed. One whose card
// no longer exists reads as missing and never blocks, so deleting a card can
// never strand every card that referenced it.
const DEPENDENCY_STATUS_DONE = "done";
const DEPENDENCY_STATUS_PENDING = "pending";
const DEPENDENCY_STATUS_MISSING = "missing";

function cleanDependencyBlockMode(value) {
  const mode = textLine(value).toLowerCase();
  return DEPENDENCY_BLOCK_MODES.includes(mode) ? mode : DEPENDENCY_BLOCK_NONE;
}

/**
 * Normalizes a dependency collection: one entry per referenced card, each with
 * a valid blocking mode. Entries without a usable card id are dropped.
 */
function normalizeDependencies(dependencies) {
  const seen = new Set();
  return (Array.isArray(dependencies) ? dependencies : [])
    .map((dependency) => ({
      cardId: cleanKanuxId(dependency && dependency.cardId),
      blocking: cleanDependencyBlockMode(dependency && dependency.blocking),
    }))
    .filter((dependency) => dependency.cardId)
    .filter((dependency) => (seen.has(dependency.cardId) ? false : seen.add(dependency.cardId)));
}

/**
 * Reads the compact storage format "cardId|mode,cardId2|mode2" shared by the
 * card frontmatter and the checklist heading comment.
 */
function parseDependencies(raw) {
  const entries = String(raw || "")
    .split(",")
    .map((part) => part.trim())
    .filter(Boolean)
    .map((part) => {
      const [cardId, blocking] = part.split("|").map((piece) => (piece || "").trim());
      return { cardId, blocking };
    });
  return normalizeDependencies(entries);
}

// Written without spaces so the same text also fits the Markdown comment that
// carries a checklist group's dependencies.
function serializeDependencies(dependencies) {
  return normalizeDependencies(dependencies)
    .map((dependency) => `${dependency.cardId}|${dependency.blocking}`)
    .join(",");
}

/**
 * Resolves how a dependency collection gates one action.
 *
 * `resolveCard` maps a card id to the card it references, or to nothing when
 * that card is gone. The gate reports every dependency with its status, the
 * ones still pending, and the strongest blocking mode among those.
 */
function dependencyGate(dependencies, resolveCard) {
  const entries = normalizeDependencies(dependencies).map((dependency) => {
    const card = resolveCard ? resolveCard(dependency.cardId) : null;
    return {
      ...dependency,
      title: card ? textLine(card.title) : "",
      status: dependencyStatus(card),
    };
  });
  const pending = entries.filter((entry) => entry.status === DEPENDENCY_STATUS_PENDING);

  return {
    entries,
    pending,
    total: entries.length,
    met: entries.filter((entry) => entry.status === DEPENDENCY_STATUS_DONE).length,
    mode: strongestBlockMode(pending),
  };
}

function dependencyStatus(card) {
  if (!card) return DEPENDENCY_STATUS_MISSING;
  return card.completed ? DEPENDENCY_STATUS_DONE : DEPENDENCY_STATUS_PENDING;
}

function strongestBlockMode(dependencies) {
  return (dependencies || []).reduce((strongest, dependency) => (
    DEPENDENCY_BLOCK_MODES.indexOf(dependency.blocking) > DEPENDENCY_BLOCK_MODES.indexOf(strongest)
      ? dependency.blocking
      : strongest
  ), DEPENDENCY_BLOCK_NONE);
}

/**
 * Reads the compact label frontmatter format: "Name|#color, Name 2|#color".
 */
function parseLabels(raw) {
  return String(raw || "")
    .split(",")
    .map((part) => part.trim())
    .filter(Boolean)
    .map((part) => {
      const [name, color] = part.split("|").map((item) => item.trim());
      return { name, color: color || "#d43c35" };
    })
    .filter((label) => label.name);
}

/**
 * Writes labels back to the same compact frontmatter format parseLabels reads.
 */
function labelsToFrontmatter(labels) {
  return (labels || [])
    .map((label) => `${textLine(label.name)}|${textLine(label.color || "#d43c35")}`)
    .join(", ");
}

/**
 * Card assignees serialize to "email|Name|#color, email2|Name2|#color2". Only the
 * email is a stable key; name/color are cached so avatars render even without a
 * live SyncDeck member list. The avatar picture is resolved live from SyncDeck.
 */
function parseAssignees(raw) {
  return String(raw || "")
    .split(",")
    .map((part) => part.trim())
    .filter(Boolean)
    .map((part) => {
      const [email, name, color] = part.split("|").map((item) => (item || "").trim());
      if (!email) return null;
      return { email, name: name || email, color: color || "#8b5cf6" };
    })
    .filter(Boolean);
}

function assigneesToFrontmatter(assignees) {
  return (assignees || [])
    .filter((a) => a && a.email)
    .map((a) => `${textLine(a.email)}|${textLine(a.name || a.email).replace(/[|,]/g, " ")}|${textLine(a.color || "#8b5cf6")}`)
    .join(", ");
}

/** Two-letter uppercase initials for an avatar fallback (no picture). */
function initials(nameOrEmail) {
  const source = String(nameOrEmail || "").trim();
  if (!source) return "?";
  const namePart = source.includes("@") ? source.split("@")[0] : source;
  const words = namePart.split(/[\s._-]+/).filter(Boolean);
  if (words.length >= 2) return (words[0][0] + words[1][0]).toUpperCase();
  return namePart.slice(0, 2).toUpperCase();
}

const CARD_METADATA_KEYS = new Set([
  "kanban-card-id",
  "kanban-board-id",
  "kanban-list-id",
  "kanux-card-code",
  "kanux-list",
  "position",
  "labels",
  "assignees",
  "completed",
  "start",
  "due",
  "depends-on",
]);

function readCardMetadata(markdown) {
  const metadata = {};
  for (const line of String(markdown || "").split(/\r?\n/)) {
    const separator = line.indexOf(":");
    if (separator < 1) continue;

    const key = line.slice(0, separator);
    if (!CARD_METADATA_KEYS.has(key) || Object.prototype.hasOwnProperty.call(metadata, key)) continue;
    metadata[key] = textLine(line.slice(separator + 1));
  }
  return metadata;
}

function optionalMetadata(metadata, key, parser) {
  if (!Object.prototype.hasOwnProperty.call(metadata, key)) return null;
  return parser(metadata[key]);
}

function numberOrNull(value) {
  if (value === undefined || value === "" || Number.isNaN(Number(value))) return null;
  return Number(value);
}

// The list structure (id/title/color/order) is embedded in the board index file
// as a base64 JSON blob inside an HTML comment, so it syncs across devices and
// survives Markdown/YAML quirks (titles can be any UTF-8 text).
const LIST_META_RE = /<!--kanux-lists:([A-Za-z0-9+/=]*)-->/;

function encodeListMeta(lists, deleted) {
  const data = {
    l: (Array.isArray(lists) ? lists : []).map((l) => ({
      i: l.id,
      t: l.title == null ? "" : String(l.title),
      c: l.color || "",
    })),
    // Sorted so an identical tombstone SET encodes to identical bytes on every
    // device — otherwise two devices that deleted lists in a different order
    // would produce different index content and churn forever.
    d: (Array.isArray(deleted) ? deleted.filter(Boolean) : []).slice().sort(),
  };
  try {
    return btoa(unescape(encodeURIComponent(JSON.stringify(data))));
  } catch (error) {
    return "";
  }
}

// Returns { lists: [{i,t,c}], deleted: [ids] } or null. Tolerates the older
// bare-array form ([{i,t,c}]) as { lists, deleted: [] }.
function decodeListMeta(markdown) {
  const match = String(markdown || "").match(LIST_META_RE);
  if (!match || !match[1]) return null;
  try {
    const obj = JSON.parse(decodeURIComponent(escape(atob(match[1]))));
    if (Array.isArray(obj)) return { lists: obj, deleted: [] };
    if (obj && typeof obj === "object") {
      return { lists: Array.isArray(obj.l) ? obj.l : [], deleted: Array.isArray(obj.d) ? obj.d : [] };
    }
    return null;
  } catch (error) {
    return null;
  }
}

/**
 * Parses a Kanux card note into the in-memory card fields.
 *
 * The parser is intentionally forgiving because users may edit these files by
 * hand. Missing frontmatter fields return empty strings or nulls so callers can
 * keep existing saved values when appropriate.
 */
function parseCardMarkdown(markdown) {
  const document = String(markdown || "");
  const metadata = readCardMetadata(document);
  const titleMatch = document.match(/^#\s+(.+)$/m);

  return {
    id: metadata["kanban-card-id"] || "",
    boardId: metadata["kanban-board-id"] || "",
    listId: metadata["kanban-list-id"] || "",
    listTitle: metadata["kanux-list"] || "",
    code: optionalMetadata(metadata, "kanux-card-code", cleanCardCode),
    position: numberOrNull(metadata.position),
    title: titleMatch ? titleMatch[1].trim() : "",
    labels: optionalMetadata(metadata, "labels", parseLabels) || [],
    assignees: optionalMetadata(metadata, "assignees", parseAssignees),
    dependencies: optionalMetadata(metadata, "depends-on", parseDependencies),
    completed: optionalMetadata(metadata, "completed", parseBoolean),
    startDate: optionalMetadata(metadata, "start", cleanDate),
    dueDate: optionalMetadata(metadata, "due", cleanDate),
    details: getSectionAny(document, ["Details", "Detaylar"]),
    checklists: parseChecklists(getSectionAny(document, ["Checklist", "Yapılacaklar", "Kontrol listesi"])),
  };
}

module.exports = {
  VIEW_TYPE,
  LEGACY_CARD_FOLDER,
  LEGACY_BOARD_INDEX_SUFFIX,
  BOARD_INDEX_MARKER,
  KANUX_ICON,
  KANUX_ICON_SVG,
  LIST_DRAG_TYPE,
  IMAGE_EXTENSIONS,
  DEFAULT_LABEL_COLOR,
  LABEL_COLORS,
  LIST_COLORS,
  DEFAULT_APPEARANCE,
  DEFAULT_DATA,
  DEPENDENCY_BLOCK_MODES,
  DEPENDENCY_BLOCK_NONE,
  DEPENDENCY_BLOCK_TOTAL,
  DEPENDENCY_BLOCK_WARN,
  DEPENDENCY_STATUS_DONE,
  DEPENDENCY_STATUS_MISSING,
  DEPENDENCY_STATUS_PENDING,
  clone,
  uid,
  textLine,
  cleanDate,
  cleanColor,
  dateFromISO,
  isoFromDate,
  addMonths,
  shortDateLabel,
  fieldDateLabel,
  dateRangeLabel,
  parseBoolean,
  labelKey,
  cleanLabelName,
  cardFileBaseName,
  kanuxListTag,
  imageTarget,
  isImagePath,
  imageRefsFromMarkdown,
  stripImageEmbeds,
  imageSizeFromMarkup,
  imageMarkupWithSize,
  moveArrayEntry,
  createElement,
  cardCodeChip,
  hasDragType,
  renderIcon,
  iconButton,
  textButton,
  addButtonIcon,
  getSection,
  getSectionAny,
  parseChecklist,
  checklistItemNoteBody,
  checklistItemNoteWithBody,
  parseChecklists,
  normalizeChecklists,
  checklistToText,
  checklistToMarkdown,
  checklistsToMarkdown,
  blankChecklists,
  checklistItems,
  checklistStats,
  cleanDependencyBlockMode,
  firstPlaceholderIndex,
  parseTemplateNumbering,
  normalizeNumbering,
  formatCardCode,
  cardCodeNumber,
  cleanCardCode,
  withNumbering,
  cleanSeparator,
  separatorChar,
  normalizeCodeLook,
  NUMBERING_KEYS,
  MAX_NUMBER_PAD,
  CODE_SEPARATORS,
  CODE_STYLES,
  CODE_PLACEMENTS,
  DEFAULT_CODE_LOOK,
  dependencyGate,
  normalizeDependencies,
  parseDependencies,
  serializeDependencies,
  parseLabels,
  labelsToFrontmatter,
  parseAssignees,
  assigneesToFrontmatter,
  initials,
  parseCardMarkdown,
  encodeListMeta,
  decodeListMeta,
};
